import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <main className={styles.contentWrapper}>
      <Head>
        <title>Arthur Freitas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={styles.menu}>
          <ul>
            <li>About</li>
            <li>Portfolio</li>
            <li>Clients</li>
            <li>Contact</li>
          </ul>
        </div>
      </header>
      <section id="home" className={styles.home}>
        <div>
          <p>Hello! 👋</p>
          <h1>I am Arthur Freitas.</h1>
          <h1>Web Developer, is the thing.</h1>
          <div>
            <p>Full Stack Developer who lives in Brazil</p>
            <p>I am hungry for knowledge and challenges are not a problem.</p>
          </div>
          <button>Portfolio</button>
        </div>
      </section>
      <section id="about" className={styles.home}>
        <div>
          <p>Hello! 👋</p>
          <h1>I am Arthur Freitas.</h1>
          <h1>Web Developer, is the thing.</h1>
          <div>
            <p>Full Stack Developer who lives in Brazil</p>
            <p>I am hungry for knowledge and challenges are not a problem.</p>
          </div>
          <button>Portfolio</button>
        </div>
      </section>
    </main>
  );
};

export default Home;
